default:
  # Select image from https://hub.docker.com/_/php
  image: php:8.1
  before_script:
    # Install dependencies
    - bash ci/docker_install.sh > /dev/null

phpunit:
  stage: test
  script:
    - phpunit --configuration tests/phpunit.xml --do-not-cache-result --log-junit phpunit-report.xml --coverage-cobertura phpunit-coverage.xml --coverage-text --colors=never
  artifacts:
    when: always
    reports:
      junit: phpunit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunit-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  only:
    - merge_requests
    - main
    - staging
